<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CheckList\Module'                        => __DIR__ . '/Module.php',
    'CheckList\Controller\TaskController' => __DIR__ . '/src/CheckList/Controller/TaskController.php',
    'CheckListTest\Framework\TestCase'        => __DIR__ . '/tests/CheckList/Framework/TestCase.php',
    'CheckListTest\SampleTest'                => __DIR__ . '/tests/CheckList/SampleTest.php',
);
